Vagrant.configure("2") do |config|
    config.vm.box = "centos/7"
    config.vm.provision :shell, inline: $script
  
    config.vm.define "master" do |server|
      server.vm.network "private_network", ip: "192.168.56.101"
      server.vm.hostname = "master"
    end
    config.vm.provider "virtualbox" do |vb|
      # 割り当てるメモリー(MB)
      vb.memory = 4000
      # CPUの数
      vb.cpus = 2
    end  
end
  
  
$script = <<END
yum -y update
yum -y install git vim wget
systemctl stop firewalld
systemctl disable firewalld


setenforce 0
sed -i 's/^SELINUX=enforcing$/SELINUX=permissive/' /etc/selinux/config


# Install Docker CE
## Set up the repository
### Install required packages.
yum install -y yum-utils device-mapper-persistent-data lvm2

### Add Docker repository.
yum-config-manager \
--add-repo \
https://download.docker.com/linux/centos/docker-ce.repo

## Install Docker CE.
yum -y update && yum -y install docker-ce-18.06.2.ce

## Create /etc/docker directory.
mkdir /etc/docker

# Setup daemon.
cat > /etc/docker/daemon.json <<EOF
{
"exec-opts": ["native.cgroupdriver=systemd"],
"log-driver": "json-file",
"log-opts": {
    "max-size": "100m"
},
"storage-driver": "overlay2",
"storage-opts": [
    "overlay2.override_kernel_check=true"
]
}
EOF

mkdir -p /etc/systemd/system/docker.service.d

# Restart Docker
systemctl daemon-reload && systemctl restart docker && systemctl enable docker


sudo usermod -aG docker vagrant
sudo swapoff -a
sed -i '/ swap / s/^\\(.*\\)$/#\\1/g' /etc/fstab

docker run -d --name=rancher --restart=unless-stopped -p 80:80 -p 443:443 rancher/rancher
END

# vagrant halt && vagrant destroy -f && vagrant up
# kubeadm init --apiserver-advertise-address=192.168.1.101 --pod-network-cidr=10.244.0.0/16
# wget https://raw.githubusercontent.com/coreos/flannel/master/Documentation/kube-flannel.yml
# kubectl apply -f kube-flannel.yml
# sudo kubeadm join 192.168.56.101:6443 --token ruubhl.8qkpgqtb1ki32ibc     --discovery-token-ca-cert-hash sha256:9c3b6ce1cee80681fd4cc13465ff46f082bc01a4d584767895f5e1ec2f7b65cd