Vagrant.configure("2") do |config|
  config.vm.box = "centos/7"
  config.vm.provision :shell, inline: $script

  config.vm.define "master" do |server|
    server.vm.network "private_network", ip: "192.168.56.101"
    server.vm.provision :shell, inline: $scriptMaster 
    server.vm.hostname = "master"
  end

  config.vm.define "node1" do |server|
    server.vm.network "private_network", ip: "192.168.56.102"
    server.vm.hostname = "node1"
  end

  config.vm.provider "virtualbox" do |vb|
    # 割り当てるメモリー(MB)
    vb.memory = 2000
    # CPUの数
    vb.cpus = 2
  end

end
